import { prisma } from '@lib/prisma'
import {
  ChurchesRepository,
  NearbyChurch,
  FindNearbyParams,
  Church,
  ChurchAlreadyExists,
} from '../../core/contracts/repository/churches-repository.interface'
import { Result, ok, err } from 'core/shared/result'
import { AppError } from 'errors/app-error'
import { ChurchNotFoundError } from '@use-cases/errors/church-not-found-error'
import { CreateChurchError } from '@use-cases/errors/create-church-error'
import { PrismaErrorMapper } from '@lib/prisma/utils/prisma-error-mapper'
import { DISTANCE_DECIMAL_PLACES, METERS_PER_KILOMETER } from 'core/constants/geo'

/**
 * KNN over a GiST index is an approximation; over-fetching and re-ranking is
 * what keeps a genuinely nearer church from being dropped by the index walk.
 */
const KNN_MIN_CANDIDATES = 100
const KNN_CANDIDATE_MULTIPLIER = 5

interface RawChurch {
  id: number
  publicId: string
  name: string
  address: string | null
  lat: number
  lon: number
  distanceMeters: number
}

/**
 * Two-phase nearest-neighbour search: a cheap index-ordered pre-filter, then an
 * exact distance calculation over the far smaller candidate set.
 */
const KNN_SQL = `
        WITH knn_candidates AS (
          -- Phase 1: Fast KNN pre-filtering using bounding box approximations
          SELECT id, geog
          FROM churches
          WHERE geog IS NOT NULL
          ORDER BY geog <-> ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography
          LIMIT $4  -- Get more candidates than needed for accuracy
        )
        -- Phase 2: Exact distance calculation and sorting on the smaller candidate set
        SELECT
          c.id,
          c.public_id as "publicId",
          c.name,
          c.address,
          c.lat,
          c.lon,
          ST_Distance(
            c.geog,
            ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography
          ) as "distanceMeters"
        FROM knn_candidates knn
        JOIN churches c ON c.id = knn.id
        ORDER BY ST_Distance(
          c.geog,
          ST_SetSRID(ST_MakePoint($2, $1), 4326)::geography
        ) ASC
        LIMIT $3  -- Final accurate results
      `

/**
 * Postgres reads `statement_timeout = 0` as *no limit at all*, so a spent or
 * sub-millisecond budget must never round down to zero — that would turn the
 * tightest deadline into an unbounded query, the exact opposite of the intent.
 */
function toStatementTimeout(timeoutMs: number): number {
  return Math.max(1, Math.floor(timeoutMs))
}

/** `geog` is generated by the database, so the row is read back after insert. */
function insertChurch(data: Omit<Church, 'id' | 'publicId' | 'createdAt' | 'updatedAt' | 'geog'>) {
  return prisma.$queryRaw<Church[]>`
        INSERT INTO churches (public_id, name, address, lat, lon, created_at, updated_at)
        VALUES (
          gen_random_uuid()::text,
          ${data.name},
          ${data.address},
          ${data.lat},
          ${data.lon},
          NOW(),
          NOW()
          )
        RETURNING
          id,
          public_id AS "publicId",
          name,
          address,
          lat,
          lon,
          geog::text AS geog,
          created_at AS "createdAt",
          updated_at AS "updatedAt"
      `
}

function toNearbyChurch(church: RawChurch): NearbyChurch {
  return {
    ...church,
    distanceMeters: Number.parseFloat(church.distanceMeters.toFixed(DISTANCE_DECIMAL_PLACES)),
    distanceKm: Number.parseFloat((church.distanceMeters / METERS_PER_KILOMETER).toFixed(DISTANCE_DECIMAL_PLACES)),
  }
}

export class PrismaChurchesRepository implements ChurchesRepository {
  constructor(private readonly errorMapper: PrismaErrorMapper<AppError>) {}

  async findNearest({
    userLat,
    userLon,
    limit = 20,
    timeoutMs,
  }: FindNearbyParams): Promise<Result<NearbyChurch[], AppError>> {
    try {
      const churches = await this.runKnnQuery(userLat, userLon, limit, timeoutMs)

      return ok(churches.map(toNearbyChurch))
    } catch (error) {
      return err(this.errorMapper.mapToKnownError(error))
    }
  }

  /**
   * Runs the KNN search, optionally under a Postgres-enforced ceiling.
   *
   * The driver cannot cancel a statement that is already executing, so a
   * request budget means nothing to this leg unless the database itself
   * enforces it. `SET LOCAL` only applies inside a transaction, which is why
   * the bounded path costs a BEGIN/COMMIT the unbounded one does not — so the
   * transaction is taken only when a ceiling was actually asked for.
   */
  private async runKnnQuery(userLat: number, userLon: number, limit: number, timeoutMs?: number): Promise<RawChurch[]> {
    // For small datasets, we use a safety margin of 5x the requested limit.
    // This ensures KNN approximations don't exclude actual nearest churches.
    const knnCandidates = Math.max(KNN_MIN_CANDIDATES, limit * KNN_CANDIDATE_MULTIPLIER)

    if (timeoutMs === undefined) {
      return await prisma.$queryRawUnsafe<RawChurch[]>(KNN_SQL, userLat, userLon, limit, knnCandidates)
    }

    return await prisma.$transaction(async (tx) => {
      await tx.$executeRawUnsafe(`SET LOCAL statement_timeout = ${toStatementTimeout(timeoutMs)}`)

      return await tx.$queryRawUnsafe<RawChurch[]>(KNN_SQL, userLat, userLon, limit, knnCandidates)
    })
  }

  async findByParams(params: ChurchAlreadyExists): Promise<Result<Church | null, AppError>> {
    try {
      const results = await prisma.$queryRaw<Church[]>`
        SELECT
          id,
          public_id as "publicId",
          name,
          address,
          lat,
          lon,
          geog::text as geog,
          created_at as "createdAt",
          updated_at as "updatedAt"
        FROM churches
        WHERE 
          lower(trim(name)) = lower(trim(${params.name}))
          OR
          (
            round(lat::numeric, 6) = round(${params.lat}::numeric, 6)
            AND
            round(lon::numeric, 6) = round(${params.lon}::numeric, 6)
          )
        LIMIT 1
      `
      return ok(results[0] ?? null)
    } catch (error) {
      return err(this.errorMapper.mapToKnownError(error))
    }
  }

  async findByName(name: string): Promise<Result<Church | null, AppError>> {
    try {
      const results = await prisma.$queryRaw<Church[]>`
        SELECT
          id,
          public_id as "publicId",
          name,
          address,
          lat,
          lon,
          geog::text as geog,
          created_at as "createdAt",
          updated_at as "updatedAt"
        FROM churches
        WHERE lower(trim(name)) = lower(trim(${name}))
        LIMIT 1
      `
      return ok(results[0] ?? null)
    } catch (error) {
      return err(this.errorMapper.mapToKnownError(error))
    }
  }

  async createChurch(
    data: Omit<Church, 'id' | 'publicId' | 'createdAt' | 'updatedAt' | 'geog'>,
  ): Promise<Result<Church, AppError>> {
    try {
      // `.at(0)` rather than destructuring: it returns `Church | undefined`,
      // so the guard below is one the type system agrees is needed.
      const inserted = await insertChurch(data)
      const church = inserted.at(0)

      if (!church) {
        return err(new CreateChurchError())
      }

      return ok(church)
    } catch (error) {
      return err(this.errorMapper.mapToKnownError(error))
    }
  }

  async deleteChurchByPublicId(publicId: string): Promise<Result<Church, AppError>> {
    try {
      const rows = await prisma.$queryRaw<Church[]>`
        DELETE FROM churches 
        WHERE public_id = ${publicId}
        RETURNING
          id,
          public_id AS "publicId",
          name,
          address,
          lat,
          lon,
          geog::text AS geog,
          created_at AS "createdAt",
          updated_at AS "updatedAt"
      `
      const church = rows.at(0)

      if (!church) {
        return err(new ChurchNotFoundError())
      }

      return ok(church)
    } catch (error) {
      return err(this.errorMapper.mapToKnownError(error))
    }
  }
}
